[package]
name = "jam-rs"
version = "0.9.10"
edition = "2024"
repository = "https://github.com/St4NNi/jam-rs"
license = "MIT"
authors = ["Sebastian Beyvers <sebastian.beyvers@cb.jlug.de>"]
description = "Just another (genomic) minhash (Jam) implementation in Rust"
keywords = [
    "minhash",
    "metagenomics",
    "bioinformatics",
    "containment",
    "jaccard",
]
categories = ["command-line-utilities", "science", "algorithms"]
exclude = ["/tests"]
readme = "README.md"


[[bin]]
name = "jam"
path = "src/main.rs"

[lib]
name = "jam_rs"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.101"
dashmap = "6.1.0"
jamhash = "0.1.2"
needletail = { version = "0.6.3", features = [
    "flate2",
    "bzip2",
    "xz2",
    "zstd",
] }
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.57", features = ["derive"] }
tempfile = "3.24.0"
crossfire = "3.0.4"
bytemuck = { version = "1.25.0", features = ["derive"] }
memmap2 = "0.9"
xorf = { version = "0.12", features = ["serde"] }
thiserror = "2"
indicatif = "0.18.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
jamhash = "0.1.2"
murmurhash3 = { version = "0.0.5" }
fastmurmur3 = "0.2.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
roaring = "0.11.3"
rand = "0.9.2"
foldhash = "0.2.0"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
