[package]
name = "jam-rs"
version = "0.9.9"
edition = "2024"
repository = "https://github.com/St4NNi/jam-rs"
license = "MIT"
authors = ["Sebastian Beyvers <sebastian.beyvers@cb.jlug.de>"]
description = "Just another (genomic) minhash (Jam) implementation in Rust"
keywords = [
    "minhash",
    "metagenomics",
    "bioinformatics",
    "containment",
    "jaccard",
]
categories = ["command-line-utilities", "science", "algorithms"]
exclude = ["/tests"]
readme = "README.md"


[[bin]]
name = "jam"
path = "src/main.rs"

[lib]
name = "jam_rs"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
jamhash = "0.1.2"
needletail = "0.6.3"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
clap = { version = "4.5.54", features = ["derive"] }
itertools = "0.14.0"
indicatif = { version = "0.18.3", features = ["rayon"] }
tempfile = "3.24.0"
crossfire = "3.0.2"
serde_json = "1.0.149"
bytemuck = { version = "1", features = ["derive"] }
memmap2 = "0.9"
xorf = { version = "0.12", features = ["serde"] }
postcard = { version = "1", features = ["alloc"] }
parking_lot = "0.12"
thiserror = "2"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }
jamhash = "0.1.2"
murmurhash3 = { version = "0.0.5" }
fastmurmur3 = "0.2.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
roaring = "0.11.3"
rand = "0.9.2"
foldhash = "0.2.0"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
